#CONFIGURATION FILE
clickDelay: 14
disableWeather: true
disableTimeCycle: true
debug: false # set to true to enable debug messages
disableMobSpawn: true
disablePlayerDamage: true # set to false to enable player damage
coinUpdateFrequency: 5 # in seconds
regenDelay: 5 # in seconds
blocks:
  STONE: 75
  IRON_ORE: 10
  GOLD_ORE: 5
  DIAMOND_ORE: 3
  GOLD_BLOCK: 5
  DIAMOND_BLOCK: 1.9
  EMERALD_BLOCK: 0.1
blockCoins:
  STONE: 0
  IRON_ORE: 1
  GOLD_ORE: 3
  DIAMOND_ORE: 5
  GOLD_BLOCK: 10
  DIAMOND_BLOCK: 12
  EMERALD_BLOCK: 50