#CONFIGURATION FILE
clickDelay: 14
disableWeather: true
disableTimeCycle: true
giveNightVision: true # set to false to disable night vision
disableHunger: true # set to false to enable hunger
debug: false # set to true to enable debug messages
disableMobSpawn: true
startupTime: 6000 # set to desired startup time (6000 is noon)
startupWeather: clear # set to desired startup weather (clear, rain, or thunder)
disablePlayerDamage: true # set to false to enable player damage
coinUpdateFrequency: 3 # in seconds
regenDelay: 45 # in seconds
blocks:
  STONE: 75
  IRON_ORE: 10
  GOLD_ORE: 5
  DIAMOND_ORE: 3
  GOLD_BLOCK: 5
  DIAMOND_BLOCK: 1.9
  EMERALD_BLOCK: 0.1
blockCoins:
  STONE: 0
  IRON_ORE: 1
  GOLD_ORE: 3
  DIAMOND_ORE: 5
  GOLD_BLOCK: 10
  DIAMOND_BLOCK: 12
  EMERALD_BLOCK: 50