#CONFIGURATION FILE
clickDelay: 14
disableWeather: true
disableTimeCycle: true
debug: false # set to true to enable debug messages
disableMobSpawn: true
coinUpdateFrequency: 5 # in seconds
regenDelay: 5 # in seconds
blocks:
  STONE: 80
  DIAMOND_ORE: 10
  GOLD_BLOCK: 8
  DIAMOND_BLOCK: 1.9
  EMERALD_BLOCK: 0.1
blockCoins:
  STONE: 0
  DIAMOND_ORE: 20
  GOLD_BLOCK: 15
  DIAMOND_BLOCK: 30
  EMERALD_BLOCK: 50